### PR TITLE
SA-21102#Side-by-side item template does not appear in item where cur…

### PR DESCRIPTION
**Pull request by tarandeepsingh-powerschool**
…sor is placed

### CODE REVIEW

**Comment by AnoopLekshminivas-PowerSchool** [comment]
hey @aaronbrooks-powerschool please review this

**Comment by aaronbrooks-powerschool** [comment]
approved!

**Review by aaronbrooks-powerschool — APPROVED** [review]

**Comment by AnoopLekshminivas-PowerSchool** [comment]
@aaronbrooks-powerschool  Thanks

**Review by AnoopLekshminivas-PowerSchool — APPROVED** [review]
approved

**Review by gouravroy-powerschool — COMMENTED** [review]
Looks fine.

**Pull request merged**
